const url = [
  {
    id: 1,
    name: "Affenpinscher",
    height: "23 - 29 Cms",
    weight: "3 - 6 Kg",
    life_span: "10 - 12 years",
    temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
    image: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
    create: false,
  },
  {
    id: 2,
    name: "Afghan Hound",
    height: "64 - 69 Cms",
    weight: "23 - 27 Kg",
    life_span: "10 - 13 years",
    temperament: "Aloof, Clownish, Dignified, Independent, Happy",
    image: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    create: false,
  },
  {
    id: 3,
    name: "African Hunting Dog",
    height: "76 Cms",
    weight: "20 - 30 Kg",
    life_span: "11 years",
    temperament: "Wild, Hardworking, Dutiful",
    image: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
    create: false,
  },
  {
    id: 4,
    name: "Airedale Terrier",
    height: "53 - 58 Cms",
    weight: "18 - 29 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
    image: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    create: false,
  },
  {
    id: 5,
    name: "Akbash Dog",
    height: "71 - 86 Cms",
    weight: "41 - 54 Kg",
    life_span: "10 - 12 years",
    temperament: "Loyal, Independent, Intelligent, Brave",
    image: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    create: false,
  },
  {
    id: 6,
    name: "Akita",
    height: "61 - 71 Cms",
    weight: "29 - 52 Kg",
    life_span: "10 - 14 years",
    temperament:
      "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
    image: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    create: false,
  },
  {
    id: 7,
    name: "Alapaha Blue Blood Bulldog",
    height: "46 - 61 Cms",
    weight: "25 - 41 Kg",
    life_span: "12 - 13 years",
    temperament: "Loving, Protective, Trainable, Dutiful, Responsible",
    image: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    create: false,
  },
  {
    id: 8,
    name: "Alaskan Husky",
    height: "58 - 66 Cms",
    weight: "17 - 23 Kg",
    life_span: "10 - 13 years",
    temperament: "Friendly, Energetic, Loyal, Gentle, Confident",
    image: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    create: false,
  },
  {
    id: 9,
    name: "Alaskan Malamute",
    height: "58 - 64 Cms",
    weight: "29 - 45 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
    image: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    create: false,
  },
  {
    id: 10,
    name: "American Bulldog",
    height: "56 - 69 Cms",
    weight: "27 - 54 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
    image: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    create: false,
  },
  {
    id: 11,
    name: "American Bully",
    height: "36 - 43 Cms",
    weight: "14 - 68 Kg",
    life_span: "8 – 15 years",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
    image: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    create: false,
  },
  {
    id: 12,
    name: "American Eskimo Dog",
    height: "38 - 48 Cms",
    weight: "9 - 18 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    image: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
    create: false,
  },
  {
    id: 13,
    name: "American Eskimo Dog (Miniature)",
    height: "23 - 30 Cms",
    weight: "3 - 5 Kg",
    life_span: "13 – 15 years",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    image: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    create: false,
  },
  {
    id: 14,
    name: "American Foxhound",
    height: "53 - 71 Cms",
    weight: "29 - 34 Kg",
    life_span: "8 - 15 years",
    temperament:
      "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
    image: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
    create: false,
  },
  {
    id: 15,
    name: "American Pit Bull Terrier",
    height: "43 - 53 Cms",
    weight: "14 - 27 Kg",
    life_span: "10 - 15 years",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
    image: "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
    create: false,
  },
  {
    id: 16,
    name: "American Staffordshire Terrier",
    height: "43 - 48 Cms",
    weight: "23 - 27 Kg",
    life_span: "12 - 15 years",
    temperament: "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
    image: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
    create: false,
  },
  {
    id: 17,
    name: "American Water Spaniel",
    height: "38 - 46 Cms",
    weight: "11 - 20 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
    image: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
    create: false,
  },
  {
    id: 18,
    name: "Anatolian Shepherd Dog",
    height: "69 - 74 Cms",
    weight: "36 - 68 Kg",
    life_span: "11 - 13 years",
    temperament: "Steady, Bold, Independent, Confident, Intelligent, Proud",
    image: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
    create: false,
  },
  {
    id: 19,
    name: "Appenzeller Sennenhund",
    height: "51 - 56 Cms",
    weight: "22 - 25 Kg",
    life_span: "12 – 14 years",
    temperament: "Reliable, Fearless, Energetic, Lively, Self-assured",
    image: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
    create: false,
  },
  {
    id: 21,
    name: "Australian Cattle Dog",
    height: "43 - 51 Cms",
    weight: "20 - 28 Kg",
    life_span: "12 - 14 years",
    temperament: "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
    image: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    create: false,
  },
  {
    id: 22,
    name: "Australian Kelpie",
    height: "43 - 51 Cms",
    weight: "14 - 21 Kg",
    life_span: "10 - 13 years",
    temperament: "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
    image: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
    create: false,
  },
  {
    id: 23,
    name: "Australian Shepherd",
    height: "46 - 58 Cms",
    weight: "16 - 29 Kg",
    life_span: "12 - 16 years",
    temperament: "Good-natured, Affectionate, Intelligent, Active, Protective",
    image: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
    create: false,
  },
  {
    id: 24,
    name: "Australian Terrier",
    height: "25 - 28 Cms",
    weight: "6 - 7 Kg",
    life_span: "15 years",
    temperament:
      "Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous",
    image: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
    create: false,
  },
  {
    id: 25,
    name: "Azawakh",
    height: "58 - 74 Cms",
    weight: "15 - 25 Kg",
    life_span: "10 - 13 years",
    temperament: "Aloof, Affectionate, Attentive, Rugged, Fierce, Refined",
    image: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
    create: false,
  },
  {
    id: 26,
    name: "Barbet",
    height: "51 - 66 Cms",
    weight: "18 - 29 Kg",
    life_span: "13 – 15 years",
    temperament: "Obedient, Companionable, Intelligent, Joyful",
    image: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
    create: false,
  },
  {
    id: 28,
    name: "Basenji",
    height: "41 - 43 Cms",
    weight: "10 - 11 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Affectionate, Energetic, Alert, Curious, Playful, Intelligent",
    image: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
    create: false,
  },
  {
    id: 29,
    name: "Basset Bleu de Gascogne",
    height: "33 - 38 Cms",
    weight: "16 - 18 Kg",
    life_span: "10 - 14 years",
    temperament: "Affectionate, Lively, Agile, Curious, Happy, Active",
    image: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
    create: false,
  },
  {
    id: 30,
    name: "Basset Hound",
    height: "36 Cms",
    weight: "23 - 29 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle",
    image: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
    create: false,
  },
  {
    id: 31,
    name: "Beagle",
    height: "33 - 38 Cms",
    weight: "9 - 16 Kg",
    life_span: "13 - 16 years",
    temperament:
      "Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent",
    image: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
    create: false,
  },
  {
    id: 32,
    name: "Bearded Collie",
    height: "51 - 56 Cms",
    weight: "20 - 25 Kg",
    life_span: "12 - 14 years",
    temperament: "Self-confidence, Hardy, Lively, Alert, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    create: false,
  },
  {
    id: 33,
    name: "Beauceron",
    height: "61 - 70 Cms",
    weight: "36 - 50 Kg",
    life_span: "10 - 12 years",
    temperament: "Fearless, Friendly, Intelligent, Protective, Calm",
    image: "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
    create: false,
  },
  {
    id: 34,
    name: "Bedlington Terrier",
    height: "38 - 41 Cms",
    weight: "8 - 10 Kg",
    life_span: "14 - 16 years",
    temperament: "Affectionate, Spirited, Intelligent, Good-tempered",
    image: "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
    create: false,
  },
  {
    id: 36,
    name: "Belgian Malinois",
    height: "56 - 66 Cms",
    weight: "18 - 36 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective",
    image: "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
    create: false,
  },
  {
    id: 38,
    name: "Belgian Tervuren",
    height: "56 - 66 Cms",
    weight: "18 - 29 Kg",
    life_span: "10 - 12 years",
    temperament: "Energetic, Alert, Loyal, Intelligent, Attentive, Protective",
    image: "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
    create: false,
  },
  {
    id: 41,
    name: "Bernese Mountain Dog",
    height: "58 - 70 Cms",
    weight: "29 - 54 Kg",
    life_span: "7 - 10 years",
    temperament: "Affectionate, Loyal, Intelligent, Faithful",
    image: "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
    create: false,
  },
  {
    id: 42,
    name: "Bichon Frise",
    height: "24 - 29 Cms",
    weight: "5 - 8 Kg",
    life_span: "15 years",
    temperament: "Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive",
    image: "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
    create: false,
  },
  {
    id: 43,
    name: "Black and Tan Coonhound",
    height: "58 - 69 Cms",
    weight: "29 - 45 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable",
    image: "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
    create: false,
  },
  {
    id: 45,
    name: "Bloodhound",
    height: "58 - 69 Cms",
    weight: "36 - 50 Kg",
    life_span: "8 - 10 years",
    temperament: "Stubborn, Affectionate, Gentle, Even Tempered",
    image: "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
    create: false,
  },
  {
    id: 47,
    name: "Bluetick Coonhound",
    height: "53 - 69 Cms",
    weight: "20 - 36 Kg",
    life_span: "12 - 14 years",
    temperament: "Friendly, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
    create: false,
  },
  {
    id: 48,
    name: "Boerboel",
    height: "56 - 69 Cms",
    weight: "50 - 91 Kg",
    life_span: "10 - 12 years",
    temperament: "Obedient, Confident, Intelligent, Dominant, Territorial",
    image: "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
    create: false,
  },
  {
    id: 50,
    name: "Border Collie",
    height: "46 - 56 Cms",
    weight: "14 - 20 Kg",
    life_span: "12 - 16 years",
    temperament: "Tenacious, Keen, Energetic, Responsive, Alert, Intelligent",
    image: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
    create: false,
  },
  {
    id: 51,
    name: "Border Terrier",
    height: "28 - 41 Cms",
    weight: "5 - 7 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered",
    image: "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
    create: false,
  },
  {
    id: 53,
    name: "Boston Terrier",
    height: "41 - 43 Cms",
    weight: "5 - 11 Kg",
    life_span: "11 - 13 years",
    temperament: "Friendly, Lively, Intelligent",
    image: "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
    create: false,
  },
  {
    id: 54,
    name: "Bouvier des Flandres",
    height: "60 - 70 Cms",
    weight: "32 - 50 Kg",
    life_span: "10 - 15 years",
    temperament: "Protective, Loyal, Gentle, Intelligent, Familial, Rational",
    image: "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
    create: false,
  },
  {
    id: 55,
    name: "Boxer",
    height: "55 - 64 Cms",
    weight: "23 - 32 Kg",
    life_span: "8 - 10 years",
    temperament:
      "Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm",
    image: "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
    create: false,
  },
  {
    id: 56,
    name: "Boykin Spaniel",
    height: "36 - 46 Cms",
    weight: "11 - 18 Kg",
    life_span: "10 - 14 years",
    temperament:
      "Friendly, Energetic, Companionable, Intelligent, Eager, Trainable",
    image: "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
    create: false,
  },
  {
    id: 57,
    name: "Bracco Italiano",
    height: "55 - 67 Cms",
    weight: "25 - 40 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable",
    image: "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
    create: false,
  },
  {
    id: 58,
    name: "Briard",
    height: "56 - 69 Cms",
    weight: "32 - 41 Kg",
    life_span: "10 - 12 years",
    temperament: "Fearless, Loyal, Obedient, Intelligent, Faithful, Protective",
    image: "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
    create: false,
  },
  {
    id: 59,
    name: "Brittany",
    height: "44 - 52 Cms",
    weight: "14 - 20 Kg",
    life_span: "12 - 14 years",
    temperament: "Agile, Adaptable, Quick, Intelligent, Attentive, Happy",
    image: "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
    create: false,
  },
  {
    id: 61,
    name: "Bull Terrier",
    height: "53 - 56 Cms",
    weight: "23 - 32 Kg",
    life_span: "10 - 12 years",
    temperament: "Trainable, Protective, Sweet-Tempered, Keen, Active",
    image: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
    create: false,
  },
  {
    id: 62,
    name: "Bull Terrier (Miniature)",
    height: "25 - 36 Cms",
    weight: "11 - 15 Kg",
    life_span: "11 – 14 years",
    temperament:
      "Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial",
    image: "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
    create: false,
  },
  {
    id: 64,
    name: "Bullmastiff",
    height: "61 - 69 Cms",
    weight: "45 - 59 Kg",
    life_span: "8 - 12 years",
    temperament:
      "Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous",
    image: "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
    create: false,
  },
  {
    id: 65,
    name: "Cairn Terrier",
    height: "23 - 25 Cms",
    weight: "6 - 6 Kg",
    life_span: "14 - 15 years",
    temperament: "Hardy, Fearless, Assertive, Gay, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
    create: false,
  },
  {
    id: 67,
    name: "Cane Corso",
    height: "60 - 70 Cms",
    weight: "40 - 54 Kg",
    life_span: "10 - 11 years",
    temperament: "Trainable, Reserved, Stable, Quiet, Even Tempered, Calm",
    image: "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
    create: false,
  },
  {
    id: 68,
    name: "Cardigan Welsh Corgi",
    height: "27 - 32 Cms",
    weight: "11 - 17 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Affectionate, Devoted, Alert, Companionable, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
    create: false,
  },
  {
    id: 69,
    name: "Catahoula Leopard Dog",
    height: "51 - 66 Cms",
    weight: "23 - 43 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving",
    image: "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
    create: false,
  },
  {
    id: 70,
    name: "Caucasian Shepherd (Ovcharka)",
    height: "61 - 85 Cms",
    weight: "36 - 45 Kg",
    life_span: "10 - 12 years",
    temperament: "Alert, Quick, Dominant, Powerful, Calm, Strong",
    image: "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
    create: false,
  },
  {
    id: 71,
    name: "Cavalier King Charles Spaniel",
    height: "30 - 33 Cms",
    weight: "6 - 8 Kg",
    life_span: "10 - 14 years",
    temperament:
      "Fearless, Affectionate, Sociable, Patient, Playful, Adaptable",
    image: "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
    create: false,
  },
  {
    id: 76,
    name: "Chesapeake Bay Retriever",
    height: "53 - 66 Cms",
    weight: "25 - 36 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Affectionate, Intelligent, Quiet, Dominant, Happy, Protective",
    image: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
    create: false,
  },
  {
    id: 78,
    name: "Chinese Crested",
    height: "28 - 33 Cms",
    weight: "5 - 6 Kg",
    life_span: "10 - 14 years",
    temperament: "Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy",
    image: "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
    create: false,
  },
  {
    id: 79,
    name: "Chinese Shar-Pei",
    height: "46 - 51 Cms",
    weight: "20 - 27 Kg",
    life_span: "10 years",
    temperament:
      "Suspicious, Affectionate, Devoted, Reserved, Independent, Loving",
    image: "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
    create: false,
  },
  {
    id: 80,
    name: "Chinook",
    height: "56 - 66 Cms",
    weight: "23 - 41 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Alert, Dignified, Intelligent, Calm",
    image: "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
    create: false,
  },
  {
    id: 81,
    name: "Chow Chow",
    height: "43 - 51 Cms",
    weight: "18 - 32 Kg",
    life_span: "12 - 15 years",
    temperament: "Aloof, Loyal, Independent, Quiet",
    image: "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
    create: false,
  },
  {
    id: 84,
    name: "Clumber Spaniel",
    height: "43 - 51 Cms",
    weight: "25 - 39 Kg",
    life_span: "10 - 12 years",
    temperament: "Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted",
    image: "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
    create: false,
  },
  {
    id: 86,
    name: "Cocker Spaniel",
    height: "36 - 38 Cms",
    weight: "9 - 14 Kg",
    life_span: "12 - 15 years",
    temperament: "Trainable, Friendly, Affectionate, Playful, Quiet, Faithful",
    image: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
    create: false,
  },
  {
    id: 87,
    name: "Cocker Spaniel (American)",
    height: "36 - 38 Cms",
    weight: "9 - 14 Kg",
    life_span: "12 - 15 years",
    temperament: "Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry",
    image: "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
    create: false,
  },
  {
    id: 89,
    name: "Coton de Tulear",
    height: "23 - 28 Cms",
    weight: "4 - 7 Kg",
    life_span: "13 - 16 years",
    temperament: "Affectionate, Lively, Playful, Intelligent, Trainable, Vocal",
    image: "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
    create: false,
  },
  {
    id: 92,
    name: "Dalmatian",
    height: "48 - 58 Cms",
    weight: "23 - 25 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
    create: false,
  },
  {
    id: 94,
    name: "Doberman Pinscher",
    height: "61 - 71 Cms",
    weight: "30 - 40 Kg",
    life_span: "10 years",
    temperament:
      "Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent",
    image: "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
    create: false,
  },
  {
    id: 95,
    name: "Dogo Argentino",
    height: "60 - 69 Cms",
    weight: "36 - 45 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective",
    image: "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
    create: false,
  },
  {
    id: 98,
    name: "Dutch Shepherd",
    height: "56 - 62 Cms",
    weight: "23 - 32 Kg",
    life_span: "15 years",
    temperament: "Reliable, Affectionate, Alert, Loyal, Obedient, Trainable",
    image: "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
    create: false,
  },
  {
    id: 101,
    name: "English Setter",
    height: "61 - 64 Cms",
    weight: "20 - 36 Kg",
    life_span: "12 years",
    temperament:
      "Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented",
    image: "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
    create: false,
  },
  {
    id: 102,
    name: "English Shepherd",
    height: "46 - 58 Cms",
    weight: "20 - 30 Kg",
    life_span: "10 - 13 years",
    temperament: "Kind, Energetic, Independent, Adaptable, Intelligent, Bossy",
    image: "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
    create: false,
  },
  {
    id: 103,
    name: "English Springer Spaniel",
    height: "48 - 51 Cms",
    weight: "16 - 23 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Affectionate, Cheerful, Alert, Intelligent, Attentive, Active",
    image: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
    create: false,
  },
  {
    id: 104,
    name: "English Toy Spaniel",
    height: "25 Cms",
    weight: "4 - 6 Kg",
    life_span: "10 - 12 years",
    temperament: "Affectionate, Reserved, Playful, Gentle, Happy, Loving",
    image: "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
    create: false,
  },
  {
    id: 105,
    name: "English Toy Terrier",
    height: "25 - 30 Cms",
    weight: "3 - 4 Kg",
    life_span: "12 - 13 years",
    temperament:
      "Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable",
    image: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
    create: false,
  },
  {
    id: 107,
    name: "Eurasier",
    height: "52 - 60 Cms",
    weight: "18 - 32 Kg",
    life_span: "12 - 14 years",
    temperament: "Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm",
    image: "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
    create: false,
  },
  {
    id: 108,
    name: "Field Spaniel",
    height: "43 - 46 Cms",
    weight: "16 - 23 Kg",
    life_span: "11 - 15 years",
    temperament: "Docile, Cautious, Sociable, Sensitive, Adaptable, Familial",
    image: "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
    create: false,
  },
  {
    id: 110,
    name: "Finnish Lapphund",
    height: "41 - 53 Cms",
    weight: "15 - 24 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Keen, Faithful, Calm, Courageous",
    image: "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
    create: false,
  },
  {
    id: 111,
    name: "Finnish Spitz",
    height: "39 - 51 Cms",
    weight: "10 - 13 Kg",
    life_span: "12 - 15 years",
    temperament: "Playful, Loyal, Independent, Intelligent, Happy, Vocal",
    image: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
    create: false,
  },
  {
    id: 113,
    name: "French Bulldog",
    height: "28 - 30 Cms",
    weight: "13 Kg",
    life_span: "9 - 11 years",
    temperament:
      "Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright",
    image: "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
    create: false,
  },
  {
    id: 114,
    name: "German Pinscher",
    height: "43 - 51 Cms",
    weight: "11 - 20 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Spirited, Lively, Intelligent, Loving, Even Tempered, Familial",
    image: "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
    create: false,
  },
  {
    id: 115,
    name: "German Shepherd Dog",
    height: "56 - 66 Cms",
    weight: "23 - 41 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous",
    image: "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
    create: false,
  },
  {
    id: 116,
    name: "German Shorthaired Pointer",
    height: "53 - 64 Cms",
    weight: "20 - 32 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable",
    image: "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
    create: false,
  },
  {
    id: 119,
    name: "Giant Schnauzer",
    height: "60 - 70 Cms",
    weight: "29 - 41 Kg",
    life_span: "10 - 12 years",
    temperament: "Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful",
    image: "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
    create: false,
  },
  {
    id: 120,
    name: "Glen of Imaal Terrier",
    height: "32 - 36 Cms",
    weight: "15 - 18 Kg",
    life_span: "12 - 15 years",
    temperament: "Spirited, Agile, Loyal, Gentle, Active, Courageous",
    image: "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
    create: false,
  },
  {
    id: 121,
    name: "Golden Retriever",
    height: "55 - 61 Cms",
    weight: "25 - 34 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident",
    image: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
    create: false,
  },
  {
    id: 123,
    name: "Gordon Setter",
    height: "58 - 69 Cms",
    weight: "20 - 36 Kg",
    life_span: "10 - 12 years",
    temperament: "Fearless, Alert, Loyal, Confident, Gay, Eager",
    image: "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
    create: false,
  },
  {
    id: 124,
    name: "Great Dane",
    height: "71 - 81 Cms",
    weight: "50 - 86 Kg",
    life_span: "7 - 10 years",
    temperament: "Friendly, Devoted, Reserved, Gentle, Confident, Loving",
    image: "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
    create: false,
  },
  {
    id: 125,
    name: "Great Pyrenees",
    height: "64 - 81 Cms",
    weight: "39 - 52 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident",
    image: "https://cdn2.thedogapi.com/images/B12uzg9V7.png",
    create: false,
  },
  {
    id: 127,
    name: "Greyhound",
    height: "69 - 76 Cms",
    weight: "23 - 32 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered",
    image: "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
    create: false,
  },
  {
    id: 128,
    name: "Griffon Bruxellois",
    height: "23 - 28 Cms",
    weight: "5 Kg",
    life_span: "10 – 15 years",
    temperament:
      "Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful",
    image: "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
    create: false,
  },
  {
    id: 129,
    name: "Harrier",
    height: "46 - 56 Cms",
    weight: "18 - 27 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active",
    image: "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
    create: false,
  },
  {
    id: 130,
    name: "Havanese",
    height: "22 - 29 Cms",
    weight: "3 - 6 Kg",
    life_span: "14 - 15 years",
    temperament:
      "Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent",
    image: "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
    create: false,
  },
  {
    id: 134,
    name: "Irish Setter",
    height: "61 - 69 Cms",
    weight: "16 - 32 Kg",
    life_span: "10 - 11 years",
    temperament:
      "Affectionate, Energetic, Lively, Independent, Playful, Companionable",
    image: "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
    create: false,
  },
  {
    id: 135,
    name: "Irish Terrier",
    height: "46 Cms",
    weight: "11 - 12 Kg",
    life_span: "12 - 16 years",
    temperament:
      "Respectful, Lively, Intelligent, Dominant, Protective, Trainable",
    image: "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
    create: false,
  },
  {
    id: 137,
    name: "Irish Wolfhound",
    height: "76 - 89 Cms",
    weight: "48 - 82 Kg",
    life_span: "6 - 8 years",
    temperament:
      "Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous",
    image: "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
    create: false,
  },
  {
    id: 138,
    name: "Italian Greyhound",
    height: "33 - 38 Cms",
    weight: "3 - 7 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent",
    image: "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
    create: false,
  },
  {
    id: 140,
    name: "Japanese Chin",
    height: "20 - 28 Cms",
    weight: "2 - 4 Kg",
    life_span: "12 - 14 years",
    temperament: "Alert, Loyal, Independent, Intelligent, Loving, Cat-like",
    image: "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
    create: false,
  },
  {
    id: 141,
    name: "Japanese Spitz",
    height: "30 - 38 Cms",
    weight: "7 - 9 Kg",
    life_span: "10 – 16 years",
    temperament:
      "Affectionate, Obedient, Playful, Companionable, Intelligent, Proud",
    image: "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
    create: false,
  },
  {
    id: 142,
    name: "Keeshond",
    height: "43 - 46 Cms",
    weight: "16 - 20 Kg",
    life_span: "12 - 15 years",
    temperament: "Agile, Obedient, Playful, Quick, Sturdy, Bright",
    image: "https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg",
    create: false,
  },
  {
    id: 144,
    name: "Komondor",
    height: "65 - 70 Cms",
    weight: "36 - 45 Kg",
    life_span: "10 - 12 years",
    temperament: "Steady, Fearless, Affectionate, Independent, Gentle, Calm",
    image: "https://cdn2.thedogapi.com/images/Bko0fl547.jpg",
    create: false,
  },
  {
    id: 145,
    name: "Kooikerhondje",
    height: "36 - 41 Cms",
    weight: "9 - 14 Kg",
    life_span: "12 - 15 years",
    temperament: "Benevolent, Agile, Alert, Intelligent, Active, Territorial",
    image: "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
    create: false,
  },
  {
    id: 147,
    name: "Kuvasz",
    height: "66 - 76 Cms",
    weight: "32 - 52 Kg",
    life_span: "8 - 10 years",
    temperament:
      "Clownish, Loyal, Patient, Independent, Intelligent, Protective",
    image: "https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg",
    create: false,
  },
  {
    id: 149,
    name: "Labrador Retriever",
    height: "55 - 62 Cms",
    weight: "25 - 36 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered",
    image: "https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg",
    create: false,
  },
  {
    id: 151,
    name: "Lagotto Romagnolo",
    height: "41 - 48 Cms",
    weight: "11 - 16 Kg",
    life_span: "14 - 16 years",
    temperament: "Keen, Loyal, Companionable, Loving, Active, Trainable",
    image: "https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg",
    create: false,
  },
  {
    id: 153,
    name: "Lancashire Heeler",
    height: "25 - 30 Cms",
    weight: "3 - 6 Kg",
    life_span: "12 – 15 years",
    temperament: "Clever, Friendly, Alert, Intelligent",
    image: "https://cdn2.thedogapi.com/images/S1RGml5Em.jpg",
    create: false,
  },
  {
    id: 155,
    name: "Leonberger",
    height: "65 - 80 Cms",
    weight: "54 - 77 Kg",
    life_span: "6 - 8 years",
    temperament: "Obedient, Fearless, Loyal, Companionable, Adaptable, Loving",
    image: "https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg",
    create: false,
  },
  {
    id: 156,
    name: "Lhasa Apso",
    height: "25 - 28 Cms",
    weight: "5 - 8 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent",
    image: "https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg",
    create: false,
  },
  {
    id: 161,
    name: "Maltese",
    height: "20 - 25 Cms",
    weight: "2 - 3 Kg",
    life_span: "15 - 18 years",
    temperament:
      "Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg",
    create: false,
  },
  {
    id: 165,
    name: "Miniature American Shepherd",
    height: "33 - 46 Cms",
    weight: "9 - 18 Kg",
    life_span: "12 - 15 years",
    temperament: "Energetic, Loyal, Intelligent, Trainable",
    image: "https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg",
    create: false,
  },
  {
    id: 167,
    name: "Miniature Pinscher",
    height: "25 - 32 Cms",
    weight: "4 - 5 Kg",
    life_span: "15 years",
    temperament: "Clever, Outgoing, Friendly, Energetic, Responsive, Playful",
    image: "https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg",
    create: false,
  },
  {
    id: 168,
    name: "Miniature Schnauzer",
    height: "30 - 36 Cms",
    weight: "5 - 9 Kg",
    life_span: "12 - 14 years",
    temperament: "Fearless, Friendly, Spirited, Alert, Obedient, Intelligent",
    image: "https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg",
    create: false,
  },
  {
    id: 171,
    name: "Newfoundland",
    height: "66 - 71 Cms",
    weight: "45 - 68 Kg",
    life_span: "8 - 10 years",
    temperament: "Sweet-Tempered, Gentle, Trainable",
    image: "https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg",
    create: false,
  },
  {
    id: 172,
    name: "Norfolk Terrier",
    height: "23 - 25 Cms",
    weight: "5 - 5 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable",
    image: "https://cdn2.thedogapi.com/images/B1ADQg94X.jpg",
    create: false,
  },
  {
    id: 176,
    name: "Norwich Terrier",
    height: "25 Cms",
    weight: "5 - 5 Kg",
    life_span: "12 - 15 years",
    temperament: "Hardy, Affectionate, Energetic, Sensitive, Intelligent",
    image: "https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg",
    create: false,
  },
  {
    id: 177,
    name: "Nova Scotia Duck Tolling Retriever",
    height: "43 - 53 Cms",
    weight: "16 - 23 Kg",
    life_span: "12 - 14 years",
    temperament: "Outgoing, Alert, Patient, Intelligent, Loving",
    image: "https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg",
    create: false,
  },
  {
    id: 178,
    name: "Old English Sheepdog",
    height: "53 Cms",
    weight: "27 - 45 Kg",
    life_span: "10 - 12 years",
    temperament: "Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving",
    image: "https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg",
    create: false,
  },
  {
    id: 179,
    name: "Olde English Bulldogge",
    height: "38 - 48 Cms",
    weight: "NaN Kg",
    life_span: "9 – 14 years",
    temperament: "Friendly, Alert, Confident, Loving, Courageous, Strong",
    image: "https://cdn2.thedogapi.com/images/B1d5me547.jpg",
    create: false,
  },
  {
    id: 181,
    name: "Papillon",
    height: "20 - 28 Cms",
    weight: "1 - 5 Kg",
    life_span: "13 - 17 years",
    temperament: "Hardy, Friendly, Energetic, Alert, Intelligent, Happy",
    image: "https://cdn2.thedogapi.com/images/SkJj7e547.jpg",
    create: false,
  },
  {
    id: 183,
    name: "Pekingese",
    height: "15 - 23 Cms",
    weight: "6 Kg",
    life_span: "14 - 18 years",
    temperament:
      "Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent",
    image: "https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg",
    create: false,
  },
  {
    id: 184,
    name: "Pembroke Welsh Corgi",
    height: "25 - 30 Cms",
    weight: "11 - 14 Kg",
    life_span: "12 - 14 years",
    temperament: "Tenacious, Outgoing, Friendly, Bold, Playful, Protective",
    image: "https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg",
    create: false,
  },
  {
    id: 185,
    name: "Perro de Presa Canario",
    height: "56 - 65 Cms",
    weight: "40 - 50 Kg",
    life_span: "10 - 12 years",
    temperament: "Strong Willed, Suspicious, Gentle, Dominant, Calm",
    image: "https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg",
    create: false,
  },
  {
    id: 188,
    name: "Pharaoh Hound",
    height: "53 - 64 Cms",
    weight: "18 - 27 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Affectionate, Sociable, Playful, Intelligent, Active, Trainable",
    image: "https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg",
    create: false,
  },
  {
    id: 189,
    name: "Plott",
    height: "51 - 64 Cms",
    weight: "18 - 27 Kg",
    life_span: "12 - 14 years",
    temperament: "Bold, Alert, Loyal, Intelligent",
    image: "https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg",
    create: false,
  },
  {
    id: 193,
    name: "Pomeranian",
    height: "20 - 30 Cms",
    weight: "1 - 3 Kg",
    life_span: "15 years",
    temperament:
      "Extroverted, Friendly, Sociable, Playful, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/HJd0XecNX.jpg",
    create: false,
  },
  {
    id: 196,
    name: "Poodle (Miniature)",
    height: "28 - 38 Cms",
    weight: "7 - 8 Kg",
    life_span: "12 – 15 years",
    image: "https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg",
    create: false,
  },
  {
    id: 197,
    name: "Poodle (Toy)",
    height: "23 - 28 Cms",
    weight: "3 - 4 Kg",
    life_span: "18 years",
    image: "https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg",
    create: false,
  },
  {
    id: 201,
    name: "Pug",
    height: "25 - 30 Cms",
    weight: "6 - 8 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive",
    image: "https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg",
    create: false,
  },
  {
    id: 204,
    name: "Puli",
    height: "41 - 43 Cms",
    weight: "11 - 16 Kg",
    life_span: "12 - 16 Years years",
    temperament: "Energetic, Agile, Loyal, Obedient, Intelligent, Faithful",
    image: "https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg",
    create: false,
  },
  {
    id: 205,
    name: "Pumi",
    height: "38 - 47 Cms",
    weight: "8 - 15 Kg",
    life_span: "13 - 15 years",
    temperament: "Lively, Reserved, Intelligent, Active, Protective, Vocal",
    image: "https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg",
    create: false,
  },
  {
    id: 207,
    name: "Rat Terrier",
    height: "25 - 33 Cms",
    weight: "4 - 11 Kg",
    life_span: "12 - 18 years",
    temperament:
      "Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving",
    image: "https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg",
    create: false,
  },
  {
    id: 208,
    name: "Redbone Coonhound",
    height: "53 - 69 Cms",
    weight: "20 - 36 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Affectionate, Energetic, Independent, Companionable, Familial, Unflappable",
    image: "https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg",
    create: false,
  },
  {
    id: 209,
    name: "Rhodesian Ridgeback",
    height: "61 - 69 Cms",
    weight: "34 - 36 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent",
    image: "https://cdn2.thedogapi.com/images/By9zNgqE7.jpg",
    create: false,
  },
  {
    id: 210,
    name: "Rottweiler",
    height: "56 - 69 Cms",
    weight: "34 - 50 Kg",
    life_span: "8 - 10 years",
    temperament:
      "Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous",
    image: "https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg",
    create: false,
  },
  {
    id: 211,
    name: "Russian Toy",
    height: "19 - 27 Cms",
    weight: "1 - 3 Kg",
    life_span: "10 - 12 years",
    image: "https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg",
    create: false,
  },
  {
    id: 212,
    name: "Saint Bernard",
    height: "65 - 70 Cms",
    weight: "59 - 82 Kg",
    life_span: "7 - 10 years",
    temperament: "Friendly, Lively, Gentle, Watchful, Calm",
    image: "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
    create: false,
  },
  {
    id: 213,
    name: "Saluki",
    height: "58 - 71 Cms",
    weight: "16 - 29 Kg",
    life_span: "12 - 14 years",
    temperament: "Aloof, Reserved, Intelligent, Quiet",
    image: "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
    create: false,
  },
  {
    id: 214,
    name: "Samoyed",
    height: "48 - 60 Cms",
    weight: "23 - 27 Kg",
    life_span: "12 - 14 years",
    temperament: "Stubborn, Friendly, Sociable, Lively, Alert, Playful",
    image: "https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg",
    create: false,
  },
  {
    id: 216,
    name: "Schipperke",
    height: "25 - 33 Cms",
    weight: "5 - 7 Kg",
    life_span: "13 - 15 years",
    temperament: "Fearless, Agile, Curious, Independent, Confident, Faithful",
    image: "https://cdn2.thedogapi.com/images/SyBvVgc47.jpg",
    create: false,
  },
  {
    id: 218,
    name: "Scottish Deerhound",
    height: "71 - 81 Cms",
    weight: "32 - 59 Kg",
    life_span: "8 - 10 years",
    temperament: "Docile, Friendly, Dignified, Gentle",
    image: "https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg",
    create: false,
  },
  {
    id: 219,
    name: "Scottish Terrier",
    height: "25 Cms",
    weight: "8 - 10 Kg",
    life_span: "11 - 13 years",
    temperament: "Feisty, Alert, Independent, Playful, Quick, Self-assured",
    image: "https://cdn2.thedogapi.com/images/Bklnce5NX.jpg",
    create: false,
  },
  {
    id: 221,
    name: "Shetland Sheepdog",
    height: "33 - 41 Cms",
    weight: "14 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong",
    image: "https://cdn2.thedogapi.com/images/rJa29l9E7.jpg",
    create: false,
  },
  {
    id: 222,
    name: "Shiba Inu",
    height: "34 - 42 Cms",
    weight: "8 - 10 Kg",
    life_span: "12 - 16 years",
    temperament: "Charming, Fearless, Keen, Alert, Confident, Faithful",
    image: "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
    create: false,
  },
  {
    id: 223,
    name: "Shih Tzu",
    height: "20 - 28 Cms",
    weight: "4 - 7 Kg",
    life_span: "10 - 18 years",
    temperament:
      "Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous",
    image: "https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg",
    create: false,
  },
  {
    id: 225,
    name: "Shiloh Shepherd",
    height: "66 - 76 Cms",
    weight: "54 - 64 Kg",
    life_span: "9 – 14 years",
    temperament: "Outgoing, Loyal, Companionable, Gentle, Loving, Trainable",
    image: "https://cdn2.thedogapi.com/images/SJJxjecEX.jpg",
    create: false,
  },
  {
    id: 226,
    name: "Siberian Husky",
    height: "51 - 60 Cms",
    weight: "16 - 27 Kg",
    life_span: "12 years",
    temperament: "Outgoing, Friendly, Alert, Gentle, Intelligent",
    image: "https://cdn2.thedogapi.com/images/S17ZilqNm.jpg",
    create: false,
  },
  {
    id: 228,
    name: "Silky Terrier",
    height: "23 - 25 Cms",
    weight: "4 - 5 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Responsive, Inquisitive, Alert, Quick, Joyful",
    image: "https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg",
    create: false,
  },
  {
    id: 232,
    name: "Smooth Fox Terrier",
    height: "39 Cms",
    weight: "NaN - 8 Kg",
    life_span: "12 - 14 years",
    temperament: "Fearless, Affectionate, Alert, Playful, Intelligent, Active",
    image: "https://cdn2.thedogapi.com/images/Syszjx9Em.jpg",
    create: false,
  },
  {
    id: 233,
    name: "Soft Coated Wheaten Terrier",
    height: "41 - 46 Cms",
    weight: "14 - 18 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful",
    image: "https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg",
    create: false,
  },
  {
    id: 235,
    name: "Spanish Water Dog",
    height: "41 - 51 Cms",
    weight: "14 - 23 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent",
    image: "https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg",
    create: false,
  },
  {
    id: 236,
    name: "Spinone Italiano",
    height: "57 - 70 Cms",
    weight: "28 - 39 Kg",
    life_span: "10 - 12 years",
    temperament: "Docile, Friendly, Affectionate, Loyal, Patient, Gentle",
    image: "https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg",
    create: false,
  },
  {
    id: 238,
    name: "Staffordshire Bull Terrier",
    height: "36 - 41 Cms",
    weight: "11 - 17 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous",
    image: "https://cdn2.thedogapi.com/images/H1zSie9V7.jpg",
    create: false,
  },
  {
    id: 239,
    name: "Standard Schnauzer",
    height: "44 - 50 Cms",
    weight: "14 - 23 Kg",
    life_span: "13 - 15 years",
    temperament:
      "Trainable, Good-natured, Devoted, Lively, Playful, Intelligent",
    image: "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
    create: false,
  },
  {
    id: 242,
    name: "Swedish Vallhund",
    height: "29 - 34 Cms",
    weight: "9 - 14 Kg",
    life_span: "12 - 14 years",
    temperament: "Fearless, Friendly, Energetic, Alert, Intelligent, Watchful",
    image: "https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg",
    create: false,
  },
  {
    id: 243,
    name: "Thai Ridgeback",
    height: "51 - 61 Cms",
    weight: "16 - 25 Kg",
    life_span: "10 - 12 years",
    temperament:
      "Protective, Loyal, Independent, Intelligent, Loving, Familial",
    image: "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
    create: false,
  },
  {
    id: 244,
    name: "Tibetan Mastiff",
    height: "61 - 66 Cms",
    weight: "39 - 64 Kg",
    life_span: "10 - 14 years",
    temperament:
      "Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective",
    image: "https://cdn2.thedogapi.com/images/SkM9sec47.jpg",
    create: false,
  },
  {
    id: 245,
    name: "Tibetan Spaniel",
    height: "25 Cms",
    weight: "4 - 7 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy",
    image: "https://cdn2.thedogapi.com/images/Hyjcol947.jpg",
    create: false,
  },
  {
    id: 246,
    name: "Tibetan Terrier",
    height: "36 - 43 Cms",
    weight: "9 - 11 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive",
    image: "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
    create: false,
  },
  {
    id: 248,
    name: "Toy Fox Terrier",
    height: "20 - 28 Cms",
    weight: "2 - 4 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Spirited, Alert, Loyal, Playful, Intelligent",
    image: "https://cdn2.thedogapi.com/images/B17ase9V7.jpg",
    create: false,
  },
  {
    id: 250,
    name: "Treeing Walker Coonhound",
    height: "51 - 69 Cms",
    weight: "20 - 36 Kg",
    life_span: "10 - 13 years",
    temperament:
      "Clever, Affectionate, Confident, Intelligent, Loving, Trainable",
    image: "https://cdn2.thedogapi.com/images/SkRpsgc47.jpg",
    create: false,
  },
  {
    id: 251,
    name: "Vizsla",
    height: "53 - 61 Cms",
    weight: "23 - 29 Kg",
    life_span: "10 - 14 years",
    temperament: "Affectionate, Energetic, Loyal, Gentle, Quiet",
    image: "https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg",
    create: false,
  },
  {
    id: 253,
    name: "Weimaraner",
    height: "58 - 69 Cms",
    weight: "25 - 41 Kg",
    life_span: "12 - 15 years",
    temperament:
      "Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast",
    image: "https://cdn2.thedogapi.com/images/SyU12l9V7.jpg",
    create: false,
  },
  {
    id: 254,
    name: "Welsh Springer Spaniel",
    height: "43 - 48 Cms",
    weight: "16 - 25 Kg",
    life_span: "12 - 15 years",
    temperament: "Stubborn, Friendly, Affectionate, Loyal, Playful, Active",
    image: "https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg",
    create: false,
  },
  {
    id: 256,
    name: "West Highland White Terrier",
    height: "25 - 28 Cms",
    weight: "7 - 10 Kg",
    life_span: "15 - 20 years",
    temperament: "Hardy, Friendly, Alert, Independent, Gay, Active, Courageous",
    image: "https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg",
    create: false,
  },
  {
    id: 257,
    name: "Whippet",
    height: "46 - 56 Cms",
    weight: "11 - 16 Kg",
    life_span: "12 - 15 years",
    temperament: "Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet",
    image: "https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg",
    create: false,
  },
  {
    id: 258,
    name: "White Shepherd",
    height: "56 - 64 Cms",
    weight: "27 - 39 Kg",
    life_span: "12 – 14 years",
    temperament:
      "Self-confidence, Aloof, Fearless, Alert, Companionable, Eager",
    image: "https://cdn2.thedogapi.com/images/r14M3e9E7.jpg",
    create: false,
  },
  {
    id: 259,
    name: "Wire Fox Terrier",
    height: "33 - 41 Cms",
    weight: "7 - 9 Kg",
    life_span: "13 – 14 years",
    temperament: "Fearless, Friendly, Bold, Keen, Alert, Quick",
    image: "https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg",
    create: false,
  },
  {
    id: 260,
    name: "Wirehaired Pointing Griffon",
    height: "51 - 61 Cms",
    weight: "20 - 32 Kg",
    life_span: "12 - 14 years",
    temperament: "Loyal, Gentle, Vigilant, Trainable, Proud",
    image: "https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg",
    create: false,
  },
  {
    id: 261,
    name: "Wirehaired Vizsla",
    height: "55 - 64 Cms",
    weight: "20 - 29 Kg",
    life_span: "12 - 14 years",
    image: "https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg",
    create: false,
  },
  {
    id: 262,
    name: "Xoloitzcuintli",
    height: "25 - 58 Cms",
    weight: "4 - 14 Kg",
    life_span: "12 - 14 years",
    temperament:
      "Cheerful, Alert, Companionable, Intelligent, Protective, Calm",
    image: "https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg",
    create: false,
  },
  {
    id: 264,
    name: "Yorkshire Terrier",
    height: "20 - 23 Cms",
    weight: "2 - 3 Kg",
    life_span: "12 - 16 years",
    temperament: "Bold, Independent, Confident, Intelligent, Courageous",
    image: "https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg",
    create: false,
  },
];
module.exports = url;
